version: '2'
services:
    clickbus-elasticsearch:
        image: elasticsearch:5.6.5
        volumes:
            - ~/volumes/clickbus/elasticsearch/:/usr/share/elasticsearch/data/
        ports:
            - 9200:9200
            - 9300:9300
        command: -Enetwork.host=0.0.0.0 -Ediscovery.type=single-node
        environment:
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        networks:
            - clickbus
    clickbus-kibana:
        image: docker.elastic.co/kibana/kibana:6.4.2
        ports:
            - 5601:5601
        # volumes:
        #  - .config/kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            SERVER_NAME: kibana.example.org
            ELASTICSEARCH_URL: http://clickbus-elasticsearch:9200
        networks:
            - clickbus

networks:
  clickbus: