version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    ports:
        - 5601:5601
    # volumes:
    #  - .config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: kibana.example.org
      ELASTICSEARCH_URL: http://localhost:9200